"""Fix Expense

Revision ID: 0286e2814c7b
Revises: 9342c7c6f445
Create Date: 2023-02-06 15:51:14.685639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0286e2814c7b'
down_revision = '9342c7c6f445'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expense', 'person')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expense', sa.Column('person', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
