"""Fix

Revision ID: 5183f0696d93
Revises: 0a181a094963
Create Date: 2023-02-06 14:15:56.169743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5183f0696d93'
down_revision = '0a181a094963'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('add_to_balance', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'add_to_balance')
    # ### end Alembic commands ###
