"""Added user fields

Revision ID: 84ca3b503483
Revises: eaa017b51ec4
Create Date: 2023-02-14 12:35:41.492289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84ca3b503483'
down_revision = 'eaa017b51ec4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'account', 'user', ['user_id'], ['id'])
    op.add_column('category', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'category', 'user', ['user_id'], ['id'])
    op.add_column('currency', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'currency', 'user', ['user_id'], ['id'])
    op.add_column('expense', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'expense', 'user', ['user_id'], ['id'])
    op.add_column('income', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'income', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'income', type_='foreignkey')
    op.drop_column('income', 'user_id')
    op.drop_constraint(None, 'expense', type_='foreignkey')
    op.drop_column('expense', 'user_id')
    op.drop_constraint(None, 'currency', type_='foreignkey')
    op.drop_column('currency', 'user_id')
    op.drop_constraint(None, 'category', type_='foreignkey')
    op.drop_column('category', 'user_id')
    op.drop_constraint(None, 'account', type_='foreignkey')
    op.drop_column('account', 'user_id')
    # ### end Alembic commands ###
