"""Fix Income

Revision ID: 9342c7c6f445
Revises: fd8b74c471d5
Create Date: 2023-02-06 15:49:45.314142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9342c7c6f445'
down_revision = 'fd8b74c471d5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('income', 'company')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('income', sa.Column('company', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
