"""Fix Account

Revision ID: fd8b74c471d5
Revises: 5183f0696d93
Create Date: 2023-02-06 15:46:47.620070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd8b74c471d5'
down_revision = '5183f0696d93'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
